### ISSUE TITLE
error message not show

### ISSUE THREAD

**Issue by mramdanf** [greengrowapps/ggaforms#4]
hei thanks for awesome library,
i was facing some problem when using the library, error message not show when edittext is empty and
i still can submit the form, here is my codes:
`TypedForm<GeneralModel> form = GGAForm.startWithContext(this)
                .appendField("username", Inputs.newString(etUsername))
                .appendField("password", Inputs.newString(etPassword))
                .buildTyped(GeneralModel.class)
                .addValidator(AnnotatedValidator.newInstance());`

and this is my object field:
@NotNull
String username;
@NotNull
String password;

**Comment by greengrowapps** [comment]
Hi. Thanks for the greetings.
The @NotNull annotation only validates that this field is not null. The username and password values are empty string "". Then, they are not null. If you want also not empty strings, you should add @MinLength(length = 1) for at least have a 1 char string. If you want longer strings just change the number.
Please close the issue if this response solves it.

**Comment by mramdanf** [comment]
thanks for the response, i just have added @MinLength(length = 1) but still not get an error message and i can submit the form, i was using edittext inside TextInputLayout is that problem?

```
<android.support.design.widget.TextInputLayout
            android:layout_marginTop="8dp"
            android:layout_marginBottom="8dp"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <EditText
                android:hint="Username"
                android:id="@+id/et_username"
                android:drawableRight="@drawable/ic_account_circle_black_48dp"
                android:inputType="textEmailAddress"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"/>

        </android.support.design.widget.TextInputLayout>

        <android.support.design.widget.TextInputLayout
            android:layout_marginTop="8dp"
            android:layout_marginBottom="8dp"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <EditText
                android:hint="Password"
                android:id="@+id/et_password"
                android:drawableRight="@drawable/ic_vpn_key_black_48dp"
                android:inputType="textPassword"
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />

        </android.support.design.widget.TextInputLayout>
```

**Comment by greengrowapps** [comment]
You can use TextInputLayout directly as you can see in the sample in the TextInputLayoutActivity.

```
    TextInputLayout email = (TextInputLayout)findViewById(R.id.username);
    TextInputLayout password = (TextInputLayout)findViewById(R.id.password);
    final Button submit = (Button)findViewById(R.id.submit);

    final TypedForm<SimpleLoginForm> inputForm = GGAForm.startWithContext(this)
            .appendField("email", Inputs.newString(email))
            .appendField("password", Inputs.newString(password))
            .buildTyped(SimpleLoginForm.class)
            .addValidator(AnnotatedValidator.newInstance());
```

**Comment by mramdanf** [comment]
thanks a lot thats working :)
